import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { SummaryData } from "@/types";

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", { day: "numeric", month: "short", year: "numeric" }).format(
    new Date(value),
  );
}

export function generateClinicalSummaryPdf(summary: SummaryData) {
  const doc = new jsPDF();
  const today = new Date().toISOString().slice(0, 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("HER", 14, 18);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Confidential Medical Record", 14, 26);

  autoTable(doc, {
    startY: 36,
    head: [["Date", "Location", "Symptom", "Severity", "Clinical text"]],
    body: summary.symptomTimeline.map((symptom) => [
      formatDate(symptom.loggedAt),
      symptom.bodyLocation || "-",
      symptom.symptomType || "-",
      symptom.severity ? `${symptom.severity}/10` : "-",
      symptom.clinicalText,
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [232, 87, 122] },
  });

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY
      ? (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10
      : 120,
    head: [["Visit date", "Doctor", "Specialty", "Dismissal rate", "Outcomes"]],
    body: summary.visitHistory.map((visit) => [
      formatDate(visit.visitDate),
      visit.doctorName,
      visit.specialty,
      `${Math.round(visit.dismissalRate * 100)}%`,
      visit.symptoms.map((item) => `${item.symptomId}: ${item.outcome}`).join("; "),
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [155, 143, 217] },
  });

  const finalY =
    ((doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || 220) + 10;
  doc.setFont("helvetica", "bold");
  doc.text("Dismissal Summary", 14, finalY);
  doc.setFont("helvetica", "normal");
  doc.text(
    `${summary.dismissalSummary.totalDismissed} of ${summary.dismissalSummary.totalPresented} reported symptoms were dismissed or not addressed.`,
    14,
    finalY + 8,
  );

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.text(
      "Generated by HER - Heard, Evidenced, Recorded. This document is for personal use only.",
      14,
      286,
    );
  }

  doc.save(`HER_clinical_summary_${today}.pdf`);
}
